In [20]:
import tensorflow as tf
import numpy as np
import sys

TRAINING_FILE = '/Users/terrycho/dev/data/flight.csv'

## read training data and label
def read_data(file_name):
    try:
        csv_file = tf.train.string_input_producer([file_name],name='filename_queue')
        textReader = tf.TextLineReader()
        _,line = textReader.read(csv_file)
        year,flight,time = tf.decode_csv(line,record_defaults=[ [1900],[""],[0] ],field_delim=',')    
    except:
        print "Unexpected error:",sys.exc_info()[0]
        exit()
    return year,flight,time

def read_data_batch(file_name,batch_size=10):
    year,flight,time = read_data(file_name)
    batch_year,batch_flight,batch_time = tf.train.batch([year,flight,time],batch_size=batch_size)
    
    return  batch_year,batch_flight,batch_time

def main():
    
    print 'start session'
    #coornator 위에 코드가 있어야 한다
    #데이타를 집어 넣기 전에 미리 그래프가 만들어져 있어야 함. 
    batch_year,batch_flight,batch_time = read_data_batch(TRAINING_FILE) 
    year = tf.placeholder(tf.int32,[None,])
    flight = tf.placeholder(tf.string,[None,])
    time = tf.placeholder(tf.int32,[None,])
    
    tt = time * 10

    with tf.Session() as sess:
        try:

            coord = tf.train.Coordinator()
            threads = tf.train.start_queue_runners(sess=sess, coord=coord)

            for i in range(10):
                y_,f_,t_ = sess.run([batch_year,batch_flight,batch_time])
                #print(t_)
                print sess.run(tt,feed_dict={time:t_})
                #print time.eval()

            print 'stop batch'
            coord.request_stop()
            coord.join(threads) 
        except:
            print "Unexpected error:", sys.exc_info()[0]

main()
     

start session
[ 1210 18730 27870 54820 30620 50070   600 37570 31990 55970]
[ 8910 17490  4280 18450  7550  5070 54070  7850  2230 50520]
[11940  7870 48920  6180  1830 42600  4010 15800  2010 49020]
[ 6980 52950 33940 55650  9870 12700 15060 19960   310  3700]
[ 8170 52470 17820 62640 16230  5160 19760 25760  7360 20800]
[33390 27630 18330 18890 48440  7250  6520 33450  8270 18940]
[ 5460 33080 37480  3210 15110 20670  6900 48510  9180 21700]
[ 7470 22270  5690 29280 22550   400 29630 11340 22120 62490]
[ 3990 10940 16740 20870  6050  9700 66230 74190 13590  7470]
[66010  1620  4900  8290  1830  7080  4370 21880 25010 23500]
stop batch
